In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("session_log.csv", delimiter=';', header=None)

data.head()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,1.721333e+12,392,404,416,421,424,412,413,401,389,...,408,395,378,387,387,404,422,464,411,400
1,1.721333e+12,407,411,425,433,440,431,429,421,397,...,417,408,388,394,396,410,426,471,424,404
2,1.721333e+12,407,411,425,433,440,431,429,421,397,...,417,408,388,394,396,410,426,471,424,404
3,1.721333e+12,407,411,425,433,440,431,429,421,397,...,417,408,388,394,396,410,426,471,424,404
4,1.721333e+12,407,411,425,433,440,431,429,421,397,...,417,408,388,394,396,410,426,471,424,404

In [2]:
%matplotlib qt

import matplotlib as mpl
import matplotlib.pyplot as plt

plt.figure(figsize=(100, 12))

plt.plot(data[0], data[10])
plt.plot(data[0], data[15], color="blue")
plt.plot(data[0], data[51], color="red")
plt.plot(data[0], data[56], color="yellow")

plt.ion()

plt.xlabel('0')
plt.ylabel('1')
plt.title('Plot of DataFrame')
plt.grid(True)
plt.show()